package com.dtech.music.windows

import java.io.File
import java.io.FileOutputStream
import java.io.OutputStreamWriter
import java.util.prefs.Preferences

object CookieManager {
    private const val COOKIE_KEY = "youtube_cookie"
    private const val COOKIE_FILE_NAME = "cookies.txt"
    private val prefs = Preferences.userRoot().node("com.dtech.music.windows.cookies")

    fun saveCookie(cookieContent: String) {
        val cleanCookie = cleanCookieString(cookieContent)
        prefs.put(COOKIE_KEY, cleanCookie)
        saveCookieToFile(cleanCookie)
        println("CookieManager: Saved cookie.")
    }

    private fun cleanCookieString(cookieString: String): String {
        return cookieString.lines()
            .map { it.trim() }
            .filter { it.isNotEmpty() && !it.startsWith("#") }
            .joinToString("; ")
            .replace(Regex("expires=[^;]+;?"), "")
            .replace(Regex("path=[^;]+;?"), "")
            .replace(Regex("domain=[^;]+;?"), "")
            .replace(Regex("SameSite=[^;]+;?"), "")
            .replace(Regex("Secure;?"), "")
            .replace(Regex("HttpOnly;?"), "")
            .replace(Regex(";;+"), ";")
            .trim(' ', ';')
    }

    fun getCookie(): String {
        return prefs.get(COOKIE_KEY, "") ?: ""
    }

    fun getCookieFile(): File? {
        val file = File(COOKIE_FILE_NAME)
        return if (file.exists() && file.length() > 0) file else null
    }

    fun checkAndLogCookies() {
        val cookie = getCookie()
        if (cookie.isNotEmpty()) {
            println("CookieManager: Loaded cookie length=${cookie.length}")
        } else {
            println("CookieManager: No cookie found.")
        }
    }

    private fun saveCookieToFile(content: String) {
        try {
            val file = File(COOKIE_FILE_NAME)
            val formatContent = buildString {
                appendLine("# Netscape HTTP Cookie File")
                appendLine("# This file is generated by DTECH MUSIC")
                appendLine()
                val pairs = content.split(";")
                for (pair in pairs) {
                    val trimmed = pair.trim()
                    if (trimmed.isNotEmpty()) {
                        val eqIndex = trimmed.indexOf('=')
                        if (eqIndex > 0) {
                            val key = trimmed.substring(0, eqIndex)
                            val value = trimmed.substring(eqIndex + 1)
                            appendLine(".youtube.com\tTRUE\t/\tTRUE\t2147483647\t$key\t$value")
                        }
                    }
                }
            }
            FileOutputStream(file).use { fos ->
                OutputStreamWriter(fos, Charsets.UTF_8).use { writer ->
                    writer.write(formatContent)
                }
            }
        } catch (e: Exception) {
            println("CookieManager: Failed to save cookie to file - ${e.message}")
        }
    }
}
